[package]
name = "bark-alloc"
version = "0.1.0"
edition = "2021"

[features]
alloc = ["bytemuck/extern_crate_alloc"]
pbuf = []

[dependencies]
bytemuck = { workspace = true, optional = true }
derive_more = { workspace = true }
