[workspace]
resolver = "2"
members = [
    "bark",
    "bark-alloc",
    "bark-protocol",
]

[workspace.dependencies]
bark-alloc = { path = "bark-alloc" }
bark-protocol = { path = "bark-protocol" }

bitflags = { version = "2.4.0", features = ["bytemuck"] }
bytemuck = { version = "1.13", features = ["derive"] }
derive_more = { version = "0.99" }
rand = { version = "0.8.5", no-default-features = true }
