[package]
name = "bark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
cpal = "0.15.2"
derive_more = "0.99.17"
libc = "0.2.147"
nix = { version = "0.26.2", features = ["time", "socket", "net"], default-features = false }
static_assertions = "1.1.0"
structopt = "0.3.26"
termcolor = "1.2.0"
