[package]
name = "bark-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { workspace = true }
bytemuck = { workspace = true }
derive_more = { workspace = true }
rand = { workspace = true }
